spring:
  mail:
    host: smtp.qq.com
    username: 1527716690@qq.com
    password: stajymawpcutiegi
    port: 587
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true